#!/usr/bin/env python3

from sys import argv
from os.path import isfile

# Data is kept as a dict of `name:credit`
data = dict()

# The log is kept as a list of tuples of the following things:
# - Who payed
# - For whom was payed
# - The thing payed for
# - The amount payed
log = list()

# Set name of the bookkeeping
name = 'Bookkeeping'
# Set path for the html
default_html = 'my_bookkeeping.html'
update_mode = 'yes'

if isfile('.bookkeeper.config'):
    with open('.bookkeeper.config','r') as file:
        lines = file.read().splitlines()
        name = lines[0]
        default_html = lines[1]
        update_mode = lines[2]
        file.close()
else:
    with open('.bookkeeper.config','w') as file:
        file.write('Bookkeeping\nmy_bookkeeping.html')
        file.close()

if isfile('.bookkeeper.log'):
    with open('.bookkeeper.log','r') as file:
        lines = file.read().splitlines()
        for line in lines:
            line = line.split('~')
            payer = line[0]
            payees = line[1].split(',')
            subject = line[2]
            amount = float(line[3])
            record = (payer,payees,subject,amount)
            log.append(record)
        file.close()
        
if isfile('.bookkeeper.data'):
    with open('.bookkeeper.data','r') as file:
        lines = file.read().splitlines()
        for line in lines:
            line = line.split('~')
            data[line[0]] = float(line[1])
        file.close()

# Define a function for mutating the records
def mutate(name,amount):
    if name in data:
        data[name] += amount
    else:
        data[name] = amount

# Define a function to register payments
def pay(payer,payees,subject,amount):
    per_person = amount / len(payees)

    for payee in payees:
        mutate(payee,-per_person)

    mutate(payer,amount)

    record = (payer,payees,subject,amount)
    log.append(record)

# Print current state to HTML file
def make_html(path=default_html,name=name):
    html = str()

    html += "<!doctype html>\n"
    html += "<html>\n"
    html += "<h1>" + name + "</h1>\n"
    html += "<h2>Balance</h2>\n"
    html += "<table>\n"
    html += "<tr><th>Name</th><th>Status</th><th>Amount</th></tr>\n"
    for person in data.keys():
        html += "<tr><td>" + person + "</td><td>"
        if data[person] > 0:
            html += "credit"
        else:
            html += "debt"
        html += "</td><td>" + str(abs(data[person])) + "</td></tr>\n"
    html += "</table>\n"
    html += "<h2>Log</h2>\n"
    html += "<table>\n"
    html += "<tr><th>Payer</th><th>Payees</th><th>Subject</th><th>amount</th></tr>\n"
    for (payer,payees,subject,amount) in log:
        html += "<tr><td>" + payer + "</td>"
        html += "<td>" + " ".join(payees) + "</td>"
        html += "<td>" + subject + "</td>"
        html += "<td>" + str(amount) + "</td></tr>\n"
    html += "</table>\n"
    html += "</html>\n"

    with open(path,'w') as file:
        file.write(html)

def display(mode):
    if mode == 'config' or mode == 'all':
        print('Bookkeeping Name: ' + name)
        print('Default HTML file: ' + default_html)
        print('Auto-Update: ' + update_mode)
    if mode == 'data' or mode == 'all':
        if mode == 'all':
            print('\nBalances:')
        for person in data.keys():
            print(person + ": " + str(data[person]))
    if mode == 'log' or mode == 'all':
        if mode == 'all':
            print('\nLog:')
        for (payer,payees,subject,amount) in log:
            print('payer: ' + payer)
            print('payees: ' + ', '.join(payees))
            print('subject: ' + subject)
            print('amount: ' + str(amount) + '\n')

# Handle args
args = argv[1:]

# If no args, explain how program works
explanation = """Bookkeeper Usage:

init name path                              Set the name and the path

pay payer payee0,payee1,.. subject amount   Register payment by `payer` in name
                                              of `payee0`, `payee1`, etc. for
                                              `subject` sized `amount`

html                                        Update HTML file

set path new_path                           Set path for HTML file
    name new_name                           Set name of bookkeeping
    update {yes|no}                         Set HTML auto-updating on or off

display {config|data|log|all}               Print config, data, log, or
                                              everything to STDOUT"""


if len(args) == 0:
    print(explanation)
else:
    if args[0] == "init":
        name = args[1]
        default_html = args[2]
    elif args[0] == "pay":
        pay(args[1],args[2].split(','),args[3],float(args[4]))
        if update_mode == 'yes':
            make_html()
    elif args[0] == "html":
            make_html()
    elif args[0] == "set":
        if args[1] == "path":
            default_html = args[2]
        elif args[1] == "name":
            name = args[2]
        elif args[1] == "update":
            update_mode = args[3]
    elif args[0] == "display":
        display(args[1])


with open('.bookkeeper.config','w') as file:
    file.write(name + '\n')
    file.write(default_html + '\n')
    file.write(update_mode + '\n')
    file.close()

with open('.bookkeeper.log','w') as file:
    for (payer,payees,subject,amount) in log:
        file.write(payer + '~' + ','.join(payees) + '~' + subject + '~' + str(amount) + '\n')
    file.close()

with open('.bookkeeper.data','w') as file:
    for person in data.keys():
        file.write(person + '~' + str(data[person]) + '\n')
    file.close()
